name: SchotterSystem
main: net.sernoxcraft.schottersystem.main.Main
version: 1.1
author: Iven S. & Lukas Oe. | LvckyAPI & IloveKOHL
commands:
  pay:
    description: Bezahle andere Spieler
  balance:
    description: Zeigt dir deinen Kontostand
    aliases: b
  setmoney:
    description: Setzt einem Spieler ein bestimmte Summe
    aliases: sm
  addmoney:
    description: Fügt einem Spieler Geld hinzu
    aliases: am