name: SchotterSystem
main: net.sernoxcraft.schottersystem.main.Main
version: 1.0
author: Iven S. Lukas Oe.
commands:
  pay:
    description: Pay People for BlowJobs
  balance:
    description: Shows your Balance
    aliases: b